/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/models/arts.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ArtsModel(props) {
  const { nodes, materials } = useGLTF('models/arts.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BuildingMesh-00000'].geometry} material={materials['BuildingMat-00000']} position={[3.02, 1.238, 6.022]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00002'].geometry} material={materials['BuildingMat-00002']} position={[3.02, 0.316, 6.022]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00003'].geometry} material={materials['BuildingMat-00003']} position={[3.02, 0.316, 6.022]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00004'].geometry} material={materials['BuildingMat-00004']} position={[3.988, 1.238, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00005'].geometry} material={materials['BuildingMat-00005']} position={[3.988, 1.238, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00006'].geometry} material={materials['BuildingMat-00006']} position={[3.02, 1.238, 5.273]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00007'].geometry} material={materials['BuildingMat-00007']} position={[3.988, 0.316, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00008'].geometry} material={materials['BuildingMat-00008']} position={[3.988, 0.316, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00009'].geometry} material={materials['BuildingMat-00009']} position={[3.019, 0.316, 5.273]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00018'].geometry} material={materials['BuildingMat-00018']} position={[3.988, 0.316, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00019'].geometry} material={materials['BuildingMat-00019']} position={[3.988, 0.316, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00024'].geometry} material={materials['BuildingMat-00024']} position={[3.988, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00025'].geometry} material={materials['BuildingMat-00025']} position={[3.988, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00027'].geometry} material={materials['BuildingMat-00027']} position={[2.051, 0.316, 5.273]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00029'].geometry} material={materials['BuildingMat-00029']} position={[3.019, -0.605, 5.273]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00030'].geometry} material={materials['BuildingMat-00030']} position={[2.051, 0.316, 6.022]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00032'].geometry} material={materials['BuildingMat-00032']} position={[3.019, 0.316, 4.523]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00034'].geometry} material={materials['BuildingMat-00034']} position={[2.051, -0.605, 5.273]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00035'].geometry} material={materials['BuildingMat-00035']} position={[2.051, -0.605, 5.273]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00037'].geometry} material={materials['BuildingMat-00037']} position={[1.083, 0.316, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00038'].geometry} material={materials['BuildingMat-00038']} position={[1.083, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00040'].geometry} material={materials['BuildingMat-00040']} position={[3.988, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00041'].geometry} material={materials['BuildingMat-00041']} position={[3.988, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00042'].geometry} material={materials['BuildingMat-00042']} position={[0.114, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00047'].geometry} material={materials['BuildingMat-00047']} position={[3.019, -0.605, 4.523]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00048'].geometry} material={materials['BuildingMat-00048']} position={[3.019, -0.605, 4.523]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00049'].geometry} material={materials['BuildingMat-00049']} position={[-0.854, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00050'].geometry} material={materials['BuildingMat-00050']} position={[2.051, 0.316, 4.523]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00053'].geometry} material={materials['BuildingMat-00053']} position={[2.051, -0.605, 4.523]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00054'].geometry} material={materials['BuildingMat-00054']} position={[-1.822, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00057'].geometry} material={materials['BuildingMat-00057']} position={[3.988, 0.316, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00058'].geometry} material={materials['BuildingMat-00058']} position={[1.083, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00059'].geometry} material={materials['BuildingMat-00059']} position={[-2.791, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00060'].geometry} material={materials['BuildingMat-00060']} position={[-2.791, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00061'].geometry} material={materials['BuildingMat-00061']} position={[0.114, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00062'].geometry} material={materials['BuildingMat-00062']} position={[3.988, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00063'].geometry} material={materials['BuildingMat-00063']} position={[3.988, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00064'].geometry} material={materials['BuildingMat-00064']} position={[-3.759, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00065'].geometry} material={materials['BuildingMat-00065']} position={[3.019, 0.316, 3.774]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00066'].geometry} material={materials['BuildingMat-00066']} position={[3.019, -0.605, 3.774]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00067'].geometry} material={materials['BuildingMat-00067']} position={[3.019, -0.605, 3.774]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00068'].geometry} material={materials['BuildingMat-00068']} position={[-0.854, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00069'].geometry} material={materials['BuildingMat-00069']} position={[-0.854, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00070'].geometry} material={materials['BuildingMat-00070']} position={[-4.727, -0.605, 5.273]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00073'].geometry} material={materials['BuildingMat-00073']} position={[0.114, 0.316, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00074'].geometry} material={materials['BuildingMat-00074']} position={[-1.822, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00075'].geometry} material={materials['BuildingMat-00075']} position={[2.051, 0.316, 3.774]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00076'].geometry} material={materials['BuildingMat-00076']} position={[2.051, -0.605, 3.774]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00077'].geometry} material={materials['BuildingMat-00077']} position={[-5.696, 0.316, 6.022]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00080'].geometry} material={materials['BuildingMat-00080']} position={[1.083, 0.316, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00081'].geometry} material={materials['BuildingMat-00081']} position={[1.083, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00083'].geometry} material={materials['BuildingMat-00083']} position={[-2.791, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00084'].geometry} material={materials['BuildingMat-00084']} position={[0.114, 0.316, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00085'].geometry} material={materials['BuildingMat-00085']} position={[0.114, 0.316, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00086'].geometry} material={materials['BuildingMat-00086']} position={[1.083, 0.316, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00087'].geometry} material={materials['BuildingMat-00087']} position={[-0.854, 0.316, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00088'].geometry} material={materials['BuildingMat-00088']} position={[0.114, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00089'].geometry} material={materials['BuildingMat-00089']} position={[0.114, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00090'].geometry} material={materials['BuildingMat-00090']} position={[3.988, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00091'].geometry} material={materials['BuildingMat-00091']} position={[1.083, 1.238, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00092'].geometry} material={materials['BuildingMat-00092']} position={[0.114, 1.238, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00093'].geometry} material={materials['BuildingMat-00093']} position={[3.019, 0.316, 3.024]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00094'].geometry} material={materials['BuildingMat-00094']} position={[-3.759, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00095'].geometry} material={materials['BuildingMat-00095']} position={[0.114, 0.316, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00096'].geometry} material={materials['BuildingMat-00096']} position={[-1.822, 0.316, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00097'].geometry} material={materials['BuildingMat-00097']} position={[0.114, 1.238, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00098'].geometry} material={materials['BuildingMat-00098']} position={[0.114, 1.238, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00099'].geometry} material={materials['BuildingMat-00099']} position={[-0.854, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00100'].geometry} material={materials['BuildingMat-00100']} position={[-0.854, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00101'].geometry} material={materials['BuildingMat-00101']} position={[1.083, 0.316, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00102'].geometry} material={materials['BuildingMat-00102']} position={[3.019, -0.605, 3.024]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00103'].geometry} material={materials['BuildingMat-00103']} position={[3.019, -0.605, 3.024]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00104'].geometry} material={materials['BuildingMat-00104']} position={[-0.854, 0.316, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00105'].geometry} material={materials['BuildingMat-00105']} position={[3.988, 0.316, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00106'].geometry} material={materials['BuildingMat-00106']} position={[-4.727, -0.605, 4.523]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00109'].geometry} material={materials['BuildingMat-00109']} position={[1.083, 0.316, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00110'].geometry} material={materials['BuildingMat-00110']} position={[1.083, 0.316, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00111'].geometry} material={materials['BuildingMat-00111']} position={[2.051, -0.605, 3.024]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00112'].geometry} material={materials['BuildingMat-00112']} position={[2.051, -0.605, 3.024]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00113'].geometry} material={materials['BuildingMat-00113']} position={[-1.822, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00114'].geometry} material={materials['BuildingMat-00114']} position={[-1.822, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00115'].geometry} material={materials['BuildingMat-00115']} position={[-1.822, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00116'].geometry} material={materials['BuildingMat-00116']} position={[2.051, 0.316, 3.024]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00121'].geometry} material={materials['BuildingMat-00121']} position={[0.114, 0.316, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00122'].geometry} material={materials['BuildingMat-00122']} position={[0.114, 0.316, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00123'].geometry} material={materials['BuildingMat-00123']} position={[0.114, 0.316, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00124'].geometry} material={materials['BuildingMat-00124']} position={[0.114, 0.316, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00125'].geometry} material={materials['BuildingMat-00125']} position={[1.083, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00126'].geometry} material={materials['BuildingMat-00126']} position={[1.083, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00128'].geometry} material={materials['BuildingMat-00128']} position={[1.083, 1.238, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00129'].geometry} material={materials['BuildingMat-00129']} position={[1.083, 1.238, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00130'].geometry} material={materials['BuildingMat-00130']} position={[-2.791, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00131'].geometry} material={materials['BuildingMat-00131']} position={[-0.854, 1.238, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00134'].geometry} material={materials['BuildingMat-00134']} position={[-0.854, 1.238, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00135'].geometry} material={materials['BuildingMat-00135']} position={[-0.854, 0.316, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00136'].geometry} material={materials['BuildingMat-00136']} position={[-0.854, 0.316, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00137'].geometry} material={materials['BuildingMat-00137']} position={[0.114, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00138'].geometry} material={materials['BuildingMat-00138']} position={[0.114, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00139'].geometry} material={materials['BuildingMat-00139']} position={[0.114, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00140'].geometry} material={materials['BuildingMat-00140']} position={[3.988, -0.605, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00141'].geometry} material={materials['BuildingMat-00141']} position={[3.988, -0.605, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00142'].geometry} material={materials['BuildingMat-00142']} position={[0.114, 1.238, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00143'].geometry} material={materials['BuildingMat-00143']} position={[-3.759, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00144'].geometry} material={materials['BuildingMat-00144']} position={[-0.854, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00145'].geometry} material={materials['BuildingMat-00145']} position={[-0.854, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00146'].geometry} material={materials['BuildingMat-00146']} position={[-0.854, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00147'].geometry} material={materials['BuildingMat-00147']} position={[3.988, 0.316, 2.274]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00148'].geometry} material={materials['BuildingMat-00148']} position={[-4.727, -0.605, 3.774]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00149'].geometry} material={materials['BuildingMat-00149']} position={[3.019, -0.605, 2.274]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00150'].geometry} material={materials['BuildingMat-00150']} position={[3.019, -0.605, 2.274]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00151'].geometry} material={materials['BuildingMat-00151']} position={[2.051, 0.316, 1.525]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00152'].geometry} material={materials['BuildingMat-00152']} position={[2.051, 0.316, 1.525]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00154'].geometry} material={materials['BuildingMat-00154']} position={[1.083, 0.316, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00155'].geometry} material={materials['BuildingMat-00155']} position={[1.083, 0.316, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00156'].geometry} material={materials['BuildingMat-00156']} position={[2.051, -0.605, 2.274]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00157'].geometry} material={materials['BuildingMat-00157']} position={[2.051, -0.605, 2.274]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00158'].geometry} material={materials['BuildingMat-00158']} position={[4.956, 0.316, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00159'].geometry} material={materials['BuildingMat-00159']} position={[-1.822, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00161'].geometry} material={materials['BuildingMat-00161']} position={[2.051, 0.316, 2.274]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00162'].geometry} material={materials['BuildingMat-00162']} position={[0.114, 0.316, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00163'].geometry} material={materials['BuildingMat-00163']} position={[0.114, 0.316, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00164'].geometry} material={materials['BuildingMat-00164']} position={[0.114, 0.316, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00165'].geometry} material={materials['BuildingMat-00165']} position={[-2.791, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00166'].geometry} material={materials['BuildingMat-00166']} position={[1.083, -0.605, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00167'].geometry} material={materials['BuildingMat-00167']} position={[2.051, 1.238, 1.525]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00169'].geometry} material={materials['BuildingMat-00169']} position={[-3.759, 0.316, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00170'].geometry} material={materials['BuildingMat-00170']} position={[1.083, 1.238, 0.775]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00173'].geometry} material={materials['BuildingMat-00173']} position={[-3.759, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00174'].geometry} material={materials['BuildingMat-00174']} position={[0.114, -0.605, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00175'].geometry} material={materials['BuildingMat-00175']} position={[0.114, -0.605, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00176'].geometry} material={materials['BuildingMat-00176']} position={[3.988, -0.605, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00177'].geometry} material={materials['BuildingMat-00177']} position={[-2.791, 0.316, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00178'].geometry} material={materials['BuildingMat-00178']} position={[2.063, 1.202, 0.897]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00179'].geometry} material={materials['BuildingMat-00179']} position={[-4.727, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00180'].geometry} material={materials['BuildingMat-00180']} position={[-4.727, -0.605, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00181'].geometry} material={materials['BuildingMat-00181']} position={[2.063, -0.641, 0.897]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00182'].geometry} material={materials['BuildingMat-00182']} position={[2.063, -0.641, 0.897]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00183'].geometry} material={materials['BuildingMat-00183']} position={[2.063, -0.641, 0.897]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00184'].geometry} material={materials['BuildingMat-00184']} position={[-0.854, -0.605, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00185'].geometry} material={materials['BuildingMat-00185']} position={[-0.854, -0.605, 2.275]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00186'].geometry} material={materials['BuildingMat-00186']} position={[3.988, 0.316, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00187'].geometry} material={materials['BuildingMat-00187']} position={[5.936, -0.641, 0.897]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00188'].geometry} material={materials['BuildingMat-00188']} position={[-0.854, 0.316, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00190'].geometry} material={materials['BuildingMat-00190']} position={[3.019, -0.605, 1.525]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00191'].geometry} material={materials['BuildingMat-00191']} position={[0.126, 1.202, 0.897]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00192'].geometry} material={materials['BuildingMat-00192']} position={[-1.81, -0.641, 2.396]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00193'].geometry} material={materials['BuildingMat-00193']} position={[-1.81, -0.641, 2.396]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00195'].geometry} material={materials['BuildingMat-00195']} position={[2.051, -0.605, 1.525]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00199'].geometry} material={materials['BuildingMat-00199']} position={[0.126, -0.641, 0.897]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00200'].geometry} material={materials['BuildingMat-00200']} position={[1.083, -0.605, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00205'].geometry} material={materials['BuildingMat-00205']} position={[-3.747, -0.641, 2.396]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00206'].geometry} material={materials['BuildingMat-00206']} position={[-3.747, -0.641, 2.396]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00207'].geometry} material={materials['BuildingMat-00207']} position={[4, -0.641, 0.897]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00208'].geometry} material={materials['BuildingMat-00208']} position={[-4.727, 0.316, 3.024]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00209'].geometry} material={materials['BuildingMat-00209']} position={[0.114, -0.605, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00210'].geometry} material={materials['BuildingMat-00210']} position={[0.114, -0.605, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00213'].geometry} material={materials['BuildingMat-00213']} position={[-0.854, -0.605, 1.525]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00216'].geometry} material={materials['BuildingMat-00216']} position={[5.936, -0.641, -0.603]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00217'].geometry} material={materials['BuildingMat-00217']} position={[5.936, -0.641, -0.603]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00218'].geometry} material={materials['BuildingMat-00218']} position={[-1.81, -0.641, 0.897]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00223'].geometry} material={materials['BuildingMat-00223']} position={[-3.747, -0.641, 0.897]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00224'].geometry} material={materials['BuildingMat-00224']} position={[-3.747, -0.641, 0.897]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00225'].geometry} material={materials['BuildingMat-00225']} position={[4, -0.641, -0.603]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00226'].geometry} material={materials['BuildingMat-00226']} position={[4, -0.641, -0.603]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00231'].geometry} material={materials['BuildingMat-00231']} position={[2.063, -0.641, -0.603]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00232'].geometry} material={materials['BuildingMat-00232']} position={[0.126, -0.641, -0.602]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00233'].geometry} material={materials['BuildingMat-00233']} position={[0.126, -0.641, -0.602]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00234'].geometry} material={materials['BuildingMat-00234']} position={[5.936, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00235'].geometry} material={materials['BuildingMat-00235']} position={[5.936, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00236'].geometry} material={materials['BuildingMat-00236']} position={[-1.81, -0.641, -0.602]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00237'].geometry} material={materials['BuildingMat-00237']} position={[-1.81, -0.641, -0.602]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00238'].geometry} material={materials['BuildingMat-00238']} position={[4, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00239'].geometry} material={materials['BuildingMat-00239']} position={[4, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00240'].geometry} material={materials['BuildingMat-00240']} position={[-3.747, -0.641, -0.602]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00241'].geometry} material={materials['BuildingMat-00241']} position={[-3.747, -0.641, -0.602]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00246'].geometry} material={materials['BuildingMat-00246']} position={[2.063, -0.641, -2.102]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00249'].geometry} material={materials['BuildingMat-00249']} position={[0.126, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00250'].geometry} material={materials['BuildingMat-00250']} position={[0.126, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00253'].geometry} material={materials['BuildingMat-00253']} position={[-1.81, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00254'].geometry} material={materials['BuildingMat-00254']} position={[5.936, -0.641, -3.601]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00255'].geometry} material={materials['BuildingMat-00255']} position={[-3.747, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00256'].geometry} material={materials['BuildingMat-00256']} position={[-3.747, -0.641, -2.102]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00259'].geometry} material={materials['BuildingMat-00259']} position={[4, -0.641, -3.601]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00266'].geometry} material={materials['BuildingMat-00266']} position={[2.063, -0.641, -3.601]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00267'].geometry} material={materials['BuildingMat-00267']} position={[2.063, -0.641, -3.601]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00270'].geometry} material={materials['BuildingMat-00270']} position={[0.126, -0.641, -3.601]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00271'].geometry} material={materials['BuildingMat-00271']} position={[-1.811, -0.641, -3.601]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00272'].geometry} material={materials['BuildingMat-00272']} position={[-1.811, -0.641, -3.601]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00273'].geometry} material={materials['BuildingMat-00273']} position={[-3.747, -0.641, -3.601]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00283'].geometry} material={materials['BuildingMat-00283']} position={[2.051, 1.238, 0.775]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00284'].geometry} material={materials['BuildingMat-00284']} position={[2.063, 1.202, 0.897]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00285'].geometry} material={materials['BuildingMat-00285']} position={[1.083, 1.238, 0.026]} rotation={[0, 0, 1.571]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00286'].geometry} material={materials['BuildingMat-00286']} position={[2.051, 1.238, 0.026]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('models/arts.glb')
