/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/models/etse.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function EtseModel(props) {
  const { nodes, materials } = useGLTF('models/etse.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BuildingMesh-00110'].geometry} material={materials['BuildingMat-00110']} position={[7.754, -1.32, -4.292]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00111'].geometry} material={materials['BuildingMat-00111']} position={[7.754, -1.32, -4.292]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00114'].geometry} material={materials['BuildingMat-00114']} position={[7.754, -1.32, -2.793]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00115'].geometry} material={materials['BuildingMat-00115']} position={[7.754, -1.32, -1.294]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00116'].geometry} material={materials['BuildingMat-00116']} position={[7.754, -1.32, 0.206]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00117'].geometry} material={materials['BuildingMat-00117']} position={[7.754, 0.523, -4.292]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00118'].geometry} material={materials['BuildingMat-00118']} position={[7.754, -1.32, 1.705]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00119'].geometry} material={materials['BuildingMat-00119']} position={[7.754, -1.32, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00122'].geometry} material={materials['BuildingMat-00122']} position={[7.754, -1.32, 4.703]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00123'].geometry} material={materials['BuildingMat-00123']} position={[7.754, -1.32, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00124'].geometry} material={materials['BuildingMat-00124']} position={[7.754, -1.32, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00135'].geometry} material={materials['BuildingMat-00135']} position={[5.817, 0.523, -5.791]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00137'].geometry} material={materials['BuildingMat-00137']} position={[5.818, -1.32, -4.292]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00139'].geometry} material={materials['BuildingMat-00139']} position={[5.818, -1.32, -2.793]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00142'].geometry} material={materials['BuildingMat-00142']} position={[5.818, -1.32, 0.206]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00143'].geometry} material={materials['BuildingMat-00143']} position={[5.818, -1.32, 1.705]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00144'].geometry} material={materials['BuildingMat-00144']} position={[5.818, -1.32, 1.705]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00145'].geometry} material={materials['BuildingMat-00145']} position={[5.818, -1.32, -1.294]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00147'].geometry} material={materials['BuildingMat-00147']} position={[5.818, 0.523, 1.705]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00148'].geometry} material={materials['BuildingMat-00148']} position={[7.754, 0.523, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00149'].geometry} material={materials['BuildingMat-00149']} position={[5.818, 0.523, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00150'].geometry} material={materials['BuildingMat-00150']} position={[5.818, -1.32, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00151'].geometry} material={materials['BuildingMat-00151']} position={[5.818, -1.32, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00154'].geometry} material={materials['BuildingMat-00154']} position={[5.818, -1.32, 4.703]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00155'].geometry} material={materials['BuildingMat-00155']} position={[7.754, 0.523, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00156'].geometry} material={materials['BuildingMat-00156']} position={[5.818, -1.32, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00157'].geometry} material={materials['BuildingMat-00157']} position={[5.818, 0.523, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00174'].geometry} material={materials['BuildingMat-00174']} position={[3.881, -1.32, -4.292]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00176'].geometry} material={materials['BuildingMat-00176']} position={[3.881, -1.32, -1.294]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00177'].geometry} material={materials['BuildingMat-00177']} position={[3.881, -1.32, -2.793]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00178'].geometry} material={materials['BuildingMat-00178']} position={[3.881, -1.32, 0.206]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00179'].geometry} material={materials['BuildingMat-00179']} position={[3.881, -1.32, 0.206]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00181'].geometry} material={materials['BuildingMat-00181']} position={[3.881, 0.523, 1.705]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00182'].geometry} material={materials['BuildingMat-00182']} position={[3.881, -1.32, 1.705]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00183'].geometry} material={materials['BuildingMat-00183']} position={[5.818, 0.523, 4.703]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00185'].geometry} material={materials['BuildingMat-00185']} position={[3.881, 0.523, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00186'].geometry} material={materials['BuildingMat-00186']} position={[3.881, -1.32, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00187'].geometry} material={materials['BuildingMat-00187']} position={[3.881, -1.32, 4.703]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00188'].geometry} material={materials['BuildingMat-00188']} position={[3.881, 0.523, 4.703]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00190'].geometry} material={materials['BuildingMat-00190']} position={[3.881, -1.32, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00197'].geometry} material={materials['BuildingMat-00197']} position={[3.881, 0.523, 0.206]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00204'].geometry} material={materials['BuildingMat-00204']} position={[1.944, -1.32, -4.292]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00205'].geometry} material={materials['BuildingMat-00205']} position={[1.944, -1.32, -2.793]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00206'].geometry} material={materials['BuildingMat-00206']} position={[1.944, -1.32, -1.294]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00207'].geometry} material={materials['BuildingMat-00207']} position={[1.944, 0.523, 0.206]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00210'].geometry} material={materials['BuildingMat-00210']} position={[1.944, -1.32, 0.206]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00211'].geometry} material={materials['BuildingMat-00211']} position={[1.944, 0.523, 1.705]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00212'].geometry} material={materials['BuildingMat-00212']} position={[1.944, 0.523, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00213'].geometry} material={materials['BuildingMat-00213']} position={[3.881, 0.523, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00214'].geometry} material={materials['BuildingMat-00214']} position={[1.944, -1.32, 1.705]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00216'].geometry} material={materials['BuildingMat-00216']} position={[1.944, 0.523, 4.703]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00219'].geometry} material={materials['BuildingMat-00219']} position={[1.944, -1.32, 3.204]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00220'].geometry} material={materials['BuildingMat-00220']} position={[1.944, -1.32, 4.703]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00221'].geometry} material={materials['BuildingMat-00221']} position={[1.944, -1.32, 4.703]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00223'].geometry} material={materials['BuildingMat-00223']} position={[1.944, 0.523, -1.294]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00226'].geometry} material={materials['BuildingMat-00226']} position={[1.944, -1.32, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00227'].geometry} material={materials['BuildingMat-00227']} position={[1.944, 0.523, 6.202]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00235'].geometry} material={materials['BuildingMat-00235']} position={[0.031, 0.452, 0.448]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00236'].geometry} material={materials['BuildingMat-00236']} position={[0.031, -3.234, 0.448]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00237'].geometry} material={materials['BuildingMat-00237']} position={[0.031, -3.234, -2.55]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00238'].geometry} material={materials['BuildingMat-00238']} position={[0.031, 0.452, 3.447]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00239'].geometry} material={materials['BuildingMat-00239']} position={[0.031, -3.234, 3.447]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00240'].geometry} material={materials['BuildingMat-00240']} position={[0.031, -3.234, 3.447]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00241'].geometry} material={materials['BuildingMat-00241']} position={[0.031, -3.234, 6.445]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00258'].geometry} material={materials['BuildingMat-00258']} position={[-3.842, -3.234, -2.55]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00261'].geometry} material={materials['BuildingMat-00261']} position={[-3.842, -3.234, 0.448]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00262'].geometry} material={materials['BuildingMat-00262']} position={[-3.842, -3.234, 3.447]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00263'].geometry} material={materials['BuildingMat-00263']} position={[-3.842, 0.452, -2.55]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00264'].geometry} material={materials['BuildingMat-00264']} position={[-3.842, -3.234, 6.445]} rotation={[0, 0, 1.571]} scale={0.016} />
    </group>
  )
}

useGLTF.preload('models/etse.glb')
