/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/models/oceanografic.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OceanograficModel(props) {
  const { nodes, materials } = useGLTF('models/oceanografic.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BuildingMesh-00014'].geometry} material={materials['BuildingMat-00014']} position={[-7.819, -1.205, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00015'].geometry} material={materials['BuildingMat-00015']} position={[-9.756, -1.205, 4.781]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00017'].geometry} material={materials['BuildingMat-00017']} position={[-7.819, -1.205, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00018'].geometry} material={materials['BuildingMat-00018']} position={[-7.819, -1.205, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00019'].geometry} material={materials['BuildingMat-00019']} position={[-9.756, -1.205, 3.282]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00020'].geometry} material={materials['BuildingMat-00020']} position={[-5.883, -1.205, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00021'].geometry} material={materials['BuildingMat-00021']} position={[-7.82, -1.205, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00023'].geometry} material={materials['BuildingMat-00023']} position={[-5.883, -1.205, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00024'].geometry} material={materials['BuildingMat-00024']} position={[-9.756, -1.205, 1.783]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00025'].geometry} material={materials['BuildingMat-00025']} position={[-9.756, -1.205, 1.783]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00026'].geometry} material={materials['BuildingMat-00026']} position={[-5.883, 0.638, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00027'].geometry} material={materials['BuildingMat-00027']} position={[-5.883, 0.638, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00028'].geometry} material={materials['BuildingMat-00028']} position={[-5.883, -1.205, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00029'].geometry} material={materials['BuildingMat-00029']} position={[-7.82, -1.205, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00030'].geometry} material={materials['BuildingMat-00030']} position={[-7.82, -1.205, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00031'].geometry} material={materials['BuildingMat-00031']} position={[-9.756, -1.206, 0.283]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00032'].geometry} material={materials['BuildingMat-00032']} position={[-9.756, -1.206, 0.283]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00033'].geometry} material={materials['BuildingMat-00033']} position={[-7.82, 0.638, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00034'].geometry} material={materials['BuildingMat-00034']} position={[-3.946, -1.205, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00035'].geometry} material={materials['BuildingMat-00035']} position={[-3.946, 2.481, 9.278]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00036'].geometry} material={materials['BuildingMat-00036']} position={[-2.009, 4.324, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00037'].geometry} material={materials['BuildingMat-00037']} position={[-7.82, 0.638, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00038'].geometry} material={materials['BuildingMat-00038']} position={[-5.883, -1.205, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00039'].geometry} material={materials['BuildingMat-00039']} position={[-3.946, -1.205, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00040'].geometry} material={materials['BuildingMat-00040']} position={[-3.946, 2.481, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00041'].geometry} material={materials['BuildingMat-00041']} position={[-7.82, -1.205, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00042'].geometry} material={materials['BuildingMat-00042']} position={[-5.883, 0.638, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00043'].geometry} material={materials['BuildingMat-00043']} position={[-3.946, 0.638, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00044'].geometry} material={materials['BuildingMat-00044']} position={[-3.946, 0.638, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00045'].geometry} material={materials['BuildingMat-00045']} position={[-9.756, -1.206, -1.216]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00046'].geometry} material={materials['BuildingMat-00046']} position={[-9.756, -1.206, -1.216]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00047'].geometry} material={materials['BuildingMat-00047']} position={[-2.009, 2.481, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00048'].geometry} material={materials['BuildingMat-00048']} position={[-2.009, 2.481, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00049'].geometry} material={materials['BuildingMat-00049']} position={[-0.073, 4.323, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00050'].geometry} material={materials['BuildingMat-00050']} position={[-5.883, 0.638, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00051'].geometry} material={materials['BuildingMat-00051']} position={[-2.009, 2.481, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00052'].geometry} material={materials['BuildingMat-00052']} position={[-2.009, -1.205, 15.275]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00053'].geometry} material={materials['BuildingMat-00053']} position={[-2.009, -1.205, 15.275]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00054'].geometry} material={materials['BuildingMat-00054']} position={[-0.073, 6.166, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00055'].geometry} material={materials['BuildingMat-00055']} position={[-3.946, -1.205, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00056'].geometry} material={materials['BuildingMat-00056']} position={[-3.946, -1.205, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00057'].geometry} material={materials['BuildingMat-00057']} position={[-2.009, 4.324, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00058'].geometry} material={materials['BuildingMat-00058']} position={[-5.883, -1.205, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00059'].geometry} material={materials['BuildingMat-00059']} position={[-5.883, -1.205, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00060'].geometry} material={materials['BuildingMat-00060']} position={[-3.946, 0.638, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00061'].geometry} material={materials['BuildingMat-00061']} position={[-2.009, 4.324, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00062'].geometry} material={materials['BuildingMat-00062']} position={[-7.82, -1.205, 1.783]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00063'].geometry} material={materials['BuildingMat-00063']} position={[-7.82, -1.205, 1.783]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00064'].geometry} material={materials['BuildingMat-00064']} position={[-2.009, -1.205, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00065'].geometry} material={materials['BuildingMat-00065']} position={[-2.009, -1.205, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00066'].geometry} material={materials['BuildingMat-00066']} position={[-3.946, -1.205, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00067'].geometry} material={materials['BuildingMat-00067']} position={[-5.883, -1.205, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00068'].geometry} material={materials['BuildingMat-00068']} position={[-2.009, 0.638, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00069'].geometry} material={materials['BuildingMat-00069']} position={[-0.073, 2.48, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00070'].geometry} material={materials['BuildingMat-00070']} position={[-7.82, -1.206, 0.283]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00071'].geometry} material={materials['BuildingMat-00071']} position={[-7.82, -1.206, 0.283]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00072'].geometry} material={materials['BuildingMat-00072']} position={[-2.009, 0.638, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00073'].geometry} material={materials['BuildingMat-00073']} position={[-2.009, 2.481, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00074'].geometry} material={materials['BuildingMat-00074']} position={[-0.073, 2.48, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00075'].geometry} material={materials['BuildingMat-00075']} position={[-2.009, -1.205, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00077'].geometry} material={materials['BuildingMat-00077']} position={[-3.946, -1.205, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00078'].geometry} material={materials['BuildingMat-00078']} position={[-3.946, -1.205, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00079'].geometry} material={materials['BuildingMat-00079']} position={[-3.946, 0.638, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00080'].geometry} material={materials['BuildingMat-00080']} position={[-5.883, -1.205, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00081'].geometry} material={materials['BuildingMat-00081']} position={[-5.883, -1.205, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00082'].geometry} material={materials['BuildingMat-00082']} position={[-7.82, -1.206, -1.216]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00083'].geometry} material={materials['BuildingMat-00083']} position={[-7.82, -1.206, -1.216]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00084'].geometry} material={materials['BuildingMat-00084']} position={[-0.073, -1.205, 15.275]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00085'].geometry} material={materials['BuildingMat-00085']} position={[-2.009, -1.205, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00086'].geometry} material={materials['BuildingMat-00086']} position={[-2.009, -1.205, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00087'].geometry} material={materials['BuildingMat-00087']} position={[-3.946, -1.205, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00088'].geometry} material={materials['BuildingMat-00088']} position={[-3.946, -1.205, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00089'].geometry} material={materials['BuildingMat-00089']} position={[-0.073, 0.638, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00090'].geometry} material={materials['BuildingMat-00090']} position={[-2.009, 0.638, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00091'].geometry} material={materials['BuildingMat-00091']} position={[-2.009, 2.481, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00092'].geometry} material={materials['BuildingMat-00092']} position={[-2.009, 2.481, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00093'].geometry} material={materials['BuildingMat-00093']} position={[-5.883, -1.205, 1.783]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00094'].geometry} material={materials['BuildingMat-00094']} position={[-5.883, -1.205, 1.783]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00095'].geometry} material={materials['BuildingMat-00095']} position={[-7.82, -1.206, -2.715]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00096'].geometry} material={materials['BuildingMat-00096']} position={[-2.009, 0.638, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00097'].geometry} material={materials['BuildingMat-00097']} position={[-2.009, 0.638, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00098'].geometry} material={materials['BuildingMat-00098']} position={[-0.073, -1.205, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00099'].geometry} material={materials['BuildingMat-00099']} position={[-0.073, -1.205, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00100'].geometry} material={materials['BuildingMat-00100']} position={[-2.009, -1.205, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00101'].geometry} material={materials['BuildingMat-00101']} position={[-2.009, -1.205, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00102'].geometry} material={materials['BuildingMat-00102']} position={[-2.009, 0.638, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00103'].geometry} material={materials['BuildingMat-00103']} position={[-3.946, -1.205, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00104'].geometry} material={materials['BuildingMat-00104']} position={[-3.946, -1.205, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00105'].geometry} material={materials['BuildingMat-00105']} position={[-2.009, 0.638, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00106'].geometry} material={materials['BuildingMat-00106']} position={[-2.009, 0.638, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00107'].geometry} material={materials['BuildingMat-00107']} position={[-5.883, -1.206, 0.283]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00108'].geometry} material={materials['BuildingMat-00108']} position={[-2.009, 2.481, 9.278]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00109'].geometry} material={materials['BuildingMat-00109']} position={[-0.073, -1.205, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00110'].geometry} material={materials['BuildingMat-00110']} position={[-0.073, -1.205, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00111'].geometry} material={materials['BuildingMat-00111']} position={[-2.009, -1.205, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00112'].geometry} material={materials['BuildingMat-00112']} position={[-2.009, -1.205, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00113'].geometry} material={materials['BuildingMat-00113']} position={[-0.073, 2.48, 9.278]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00114'].geometry} material={materials['BuildingMat-00114']} position={[-3.946, -1.205, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00115'].geometry} material={materials['BuildingMat-00115']} position={[-0.073, 0.638, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00116'].geometry} material={materials['BuildingMat-00116']} position={[-2.009, 2.481, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00117'].geometry} material={materials['BuildingMat-00117']} position={[-0.073, 2.48, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00118'].geometry} material={materials['BuildingMat-00118']} position={[-0.073, 2.48, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00119'].geometry} material={materials['BuildingMat-00119']} position={[-0.073, 0.638, 9.278]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00120'].geometry} material={materials['BuildingMat-00120']} position={[-0.073, 0.638, 9.278]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00121'].geometry} material={materials['BuildingMat-00121']} position={[-5.883, -1.206, -1.216]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00122'].geometry} material={materials['BuildingMat-00122']} position={[-2.009, -1.205, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00123'].geometry} material={materials['BuildingMat-00123']} position={[-3.946, -1.206, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00124'].geometry} material={materials['BuildingMat-00124']} position={[1.864, -1.206, 15.275]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00125'].geometry} material={materials['BuildingMat-00125']} position={[-0.073, -1.205, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00126'].geometry} material={materials['BuildingMat-00126']} position={[-0.073, 0.638, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00127'].geometry} material={materials['BuildingMat-00127']} position={[-0.073, 0.638, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00128'].geometry} material={materials['BuildingMat-00128']} position={[-5.883, -1.206, -2.715]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00129'].geometry} material={materials['BuildingMat-00129']} position={[1.864, -1.206, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00130'].geometry} material={materials['BuildingMat-00130']} position={[1.864, -1.206, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00131'].geometry} material={materials['BuildingMat-00131']} position={[-0.073, -1.205, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00132'].geometry} material={materials['BuildingMat-00132']} position={[-0.073, -1.205, 9.279]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00133'].geometry} material={materials['BuildingMat-00133']} position={[-0.073, 2.48, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00134'].geometry} material={materials['BuildingMat-00134']} position={[-2.009, -1.205, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00135'].geometry} material={materials['BuildingMat-00135']} position={[-2.009, -1.205, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00136'].geometry} material={materials['BuildingMat-00136']} position={[-3.946, -1.206, 0.283]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00137'].geometry} material={materials['BuildingMat-00137']} position={[-3.946, -1.206, 0.283]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00138'].geometry} material={materials['BuildingMat-00138']} position={[-5.883, -1.206, -4.214]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00139'].geometry} material={materials['BuildingMat-00139']} position={[-0.073, 0.637, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00140'].geometry} material={materials['BuildingMat-00140']} position={[-0.073, 0.637, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00141'].geometry} material={materials['BuildingMat-00141']} position={[-2.009, 0.637, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00144'].geometry} material={materials['BuildingMat-00144']} position={[-0.073, -1.205, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00145'].geometry} material={materials['BuildingMat-00145']} position={[-3.946, 0.638, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00146'].geometry} material={materials['BuildingMat-00146']} position={[-2.01, -1.205, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00147'].geometry} material={materials['BuildingMat-00147']} position={[-2.01, -1.205, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00148'].geometry} material={materials['BuildingMat-00148']} position={[-3.946, 0.637, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00149'].geometry} material={materials['BuildingMat-00149']} position={[1.864, 0.637, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00150'].geometry} material={materials['BuildingMat-00150']} position={[1.864, -1.206, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00153'].geometry} material={materials['BuildingMat-00153']} position={[-3.946, -1.206, -1.216]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00154'].geometry} material={materials['BuildingMat-00154']} position={[-3.946, -1.206, -1.216]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00155'].geometry} material={materials['BuildingMat-00155']} position={[-2.009, 0.637, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00156'].geometry} material={materials['BuildingMat-00156']} position={[3.801, -1.206, 15.275]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00157'].geometry} material={materials['BuildingMat-00157']} position={[-0.073, -1.205, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00158'].geometry} material={materials['BuildingMat-00158']} position={[-0.073, -1.205, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00159'].geometry} material={materials['BuildingMat-00159']} position={[-2.01, -1.206, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00160'].geometry} material={materials['BuildingMat-00160']} position={[1.864, 0.637, 9.278]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00161'].geometry} material={materials['BuildingMat-00161']} position={[1.864, -1.205, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00162'].geometry} material={materials['BuildingMat-00162']} position={[-3.946, -1.206, -2.715]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00163'].geometry} material={materials['BuildingMat-00163']} position={[-3.946, -1.206, -2.715]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00164'].geometry} material={materials['BuildingMat-00164']} position={[1.864, -1.206, 9.278]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00165'].geometry} material={materials['BuildingMat-00165']} position={[3.801, -1.206, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00166'].geometry} material={materials['BuildingMat-00166']} position={[-0.073, -1.206, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00167'].geometry} material={materials['BuildingMat-00167']} position={[1.864, 0.637, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00168'].geometry} material={materials['BuildingMat-00168']} position={[-2.01, -1.206, 0.283]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00169'].geometry} material={materials['BuildingMat-00169']} position={[-2.01, -1.206, 0.283]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00170'].geometry} material={materials['BuildingMat-00170']} position={[-0.073, 0.637, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00171'].geometry} material={materials['BuildingMat-00171']} position={[-0.073, 0.637, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00172'].geometry} material={materials['BuildingMat-00172']} position={[-3.946, -1.206, -4.214]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00173'].geometry} material={materials['BuildingMat-00173']} position={[-2.01, 0.637, 0.283]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00175'].geometry} material={materials['BuildingMat-00175']} position={[1.864, -1.206, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00176'].geometry} material={materials['BuildingMat-00176']} position={[1.864, -1.206, 7.779]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00177'].geometry} material={materials['BuildingMat-00177']} position={[3.801, -1.206, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00178'].geometry} material={materials['BuildingMat-00178']} position={[-0.073, -1.206, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00179'].geometry} material={materials['BuildingMat-00179']} position={[-2.01, -1.206, -1.216]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00180'].geometry} material={materials['BuildingMat-00180']} position={[-2.01, -1.206, -1.216]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00181'].geometry} material={materials['BuildingMat-00181']} position={[-2.01, 0.637, -1.216]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00182'].geometry} material={materials['BuildingMat-00182']} position={[-3.946, -1.206, -5.714]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00183'].geometry} material={materials['BuildingMat-00183']} position={[5.737, -1.206, 15.275]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00184'].geometry} material={materials['BuildingMat-00184']} position={[5.737, -1.206, 15.275]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00185'].geometry} material={materials['BuildingMat-00185']} position={[-0.073, 0.637, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00186'].geometry} material={materials['BuildingMat-00186']} position={[3.801, -1.206, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00187'].geometry} material={materials['BuildingMat-00187']} position={[1.864, -1.206, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00188'].geometry} material={materials['BuildingMat-00188']} position={[1.864, -1.206, 6.28]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00189'].geometry} material={materials['BuildingMat-00189']} position={[-0.073, -1.206, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00190'].geometry} material={materials['BuildingMat-00190']} position={[-0.073, -1.206, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00191'].geometry} material={materials['BuildingMat-00191']} position={[5.737, 0.637, 15.275]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00192'].geometry} material={materials['BuildingMat-00192']} position={[-2.01, -1.206, -2.715]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00193'].geometry} material={materials['BuildingMat-00193']} position={[-3.947, -1.206, -7.213]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00194'].geometry} material={materials['BuildingMat-00194']} position={[-3.947, -1.206, -7.213]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00195'].geometry} material={materials['BuildingMat-00195']} position={[1.864, 0.637, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00196'].geometry} material={materials['BuildingMat-00196']} position={[5.737, -1.206, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00197'].geometry} material={materials['BuildingMat-00197']} position={[5.761, -1.276, 9.521]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00198'].geometry} material={materials['BuildingMat-00198']} position={[1.864, -1.206, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00199'].geometry} material={materials['BuildingMat-00199']} position={[1.864, -1.206, 4.781]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00200'].geometry} material={materials['BuildingMat-00200']} position={[1.888, -1.276, 0.526]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00201'].geometry} material={materials['BuildingMat-00201']} position={[1.888, -1.276, 0.526]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00202'].geometry} material={materials['BuildingMat-00202']} position={[-1.986, -1.277, -8.469]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00203'].geometry} material={materials['BuildingMat-00203']} position={[1.864, 0.637, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00204'].geometry} material={materials['BuildingMat-00204']} position={[-2.01, -1.206, -4.214]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00206'].geometry} material={materials['BuildingMat-00206']} position={[5.737, -1.206, 12.277]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00207'].geometry} material={materials['BuildingMat-00207']} position={[1.864, -1.206, 3.282]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00208'].geometry} material={materials['BuildingMat-00208']} position={[5.737, 0.637, 16.775]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00209'].geometry} material={materials['BuildingMat-00209']} position={[5.737, 0.637, 13.776]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00210'].geometry} material={materials['BuildingMat-00210']} position={[9.635, -1.276, 15.518]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00211'].geometry} material={materials['BuildingMat-00211']} position={[1.888, -1.276, -2.473]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00212'].geometry} material={materials['BuildingMat-00212']} position={[1.888, -1.276, -2.473]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00213'].geometry} material={materials['BuildingMat-00213']} position={[-2.01, -1.206, -5.714]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00214'].geometry} material={materials['BuildingMat-00214']} position={[5.761, -1.276, 6.523]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00215'].geometry} material={materials['BuildingMat-00215']} position={[5.737, -1.206, 10.778]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00216'].geometry} material={materials['BuildingMat-00216']} position={[1.864, -1.206, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00217'].geometry} material={materials['BuildingMat-00217']} position={[1.864, -1.206, 1.782]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00218'].geometry} material={materials['BuildingMat-00218']} position={[-1.986, -1.277, -11.468]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00219'].geometry} material={materials['BuildingMat-00219']} position={[-1.986, -1.277, -11.468]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00220'].geometry} material={materials['BuildingMat-00220']} position={[-2.01, -1.206, -7.213]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00221'].geometry} material={materials['BuildingMat-00221']} position={[5.761, -1.276, 3.524]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00222'].geometry} material={materials['BuildingMat-00222']} position={[5.761, -1.276, 3.524]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00223'].geometry} material={materials['BuildingMat-00223']} position={[9.635, -1.276, 12.52]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00225'].geometry} material={materials['BuildingMat-00225']} position={[1.887, -1.277, -5.471]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00226'].geometry} material={materials['BuildingMat-00226']} position={[1.887, -1.277, -5.471]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00227'].geometry} material={materials['BuildingMat-00227']} position={[5.761, -1.276, 0.526]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00229'].geometry} material={materials['BuildingMat-00229']} position={[9.635, -1.276, 9.521]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00230'].geometry} material={materials['BuildingMat-00230']} position={[1.887, -1.277, -8.47]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00231'].geometry} material={materials['BuildingMat-00231']} position={[1.887, -1.277, -8.47]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00233'].geometry} material={materials['BuildingMat-00233']} position={[5.761, -1.277, -2.473]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00234'].geometry} material={materials['BuildingMat-00234']} position={[5.761, -1.277, -2.473]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00235'].geometry} material={materials['BuildingMat-00235']} position={[9.635, -1.277, 6.523]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00236'].geometry} material={materials['BuildingMat-00236']} position={[1.887, -1.277, -11.468]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00238'].geometry} material={materials['BuildingMat-00238']} position={[5.761, -1.277, -5.471]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00239'].geometry} material={materials['BuildingMat-00239']} position={[9.634, -1.277, 3.524]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00242'].geometry} material={materials['BuildingMat-00242']} position={[5.761, -1.277, -8.47]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00243'].geometry} material={materials['BuildingMat-00243']} position={[5.761, -1.277, -8.47]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00245'].geometry} material={materials['BuildingMat-00245']} position={[9.634, -1.277, 0.526]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00247'].geometry} material={materials['BuildingMat-00247']} position={[9.634, -1.277, -2.473]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00248'].geometry} material={materials['BuildingMat-00248']} position={[9.634, -1.277, -2.473]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00250'].geometry} material={materials['BuildingMat-00250']} position={[5.76, -1.277, -11.468]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00255'].geometry} material={materials['BuildingMat-00255']} position={[9.634, -1.277, -5.472]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00256'].geometry} material={materials['BuildingMat-00256']} position={[9.634, -1.277, -8.47]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00257'].geometry} material={materials['BuildingMat-00257']} position={[9.634, -1.277, -8.47]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00258'].geometry} material={materials['BuildingMat-00258']} position={[9.634, -1.277, -8.47]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00263'].geometry} material={materials['BuildingMat-00263']} position={[9.634, -1.277, -11.469]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00264'].geometry} material={materials['BuildingMat-00264']} position={[9.634, -1.277, -11.469]} rotation={[0, 0, 1.571]} scale={0.016} />
    </group>
  )
}

useGLTF.preload('models/oceanografic.glb')
