/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/models/parcCientific.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ParcCientificModel(props) {
  const { nodes, materials } = useGLTF('models/parcCientific.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BuildingMesh-00011'].geometry} material={materials['BuildingMat-00011']} position={[11.12, -0.368, 2.965]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00014'].geometry} material={materials['BuildingMat-00014']} position={[11.12, -0.368, 3.714]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00015'].geometry} material={materials['BuildingMat-00015']} position={[11.12, -0.368, 4.464]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00017'].geometry} material={materials['BuildingMat-00017']} position={[11.12, -0.368, 5.214]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00027'].geometry} material={materials['BuildingMat-00027']} position={[10.152, -0.368, 2.215]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00028'].geometry} material={materials['BuildingMat-00028']} position={[10.152, -0.368, 2.965]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00030'].geometry} material={materials['BuildingMat-00030']} position={[10.152, -0.368, 3.714]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00033'].geometry} material={materials['BuildingMat-00033']} position={[10.152, -0.368, 4.464]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00037'].geometry} material={materials['BuildingMat-00037']} position={[10.152, -0.368, 5.214]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00040'].geometry} material={materials['BuildingMat-00040']} position={[10.152, 0.553, 3.714]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00041'].geometry} material={materials['BuildingMat-00041']} position={[10.152, -0.368, 5.963]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00045'].geometry} material={materials['BuildingMat-00045']} position={[10.164, 0.518, 5.335]} rotation={[0, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00047'].geometry} material={materials['BuildingMat-00047']} position={[9.183, -0.368, 1.466]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00049'].geometry} material={materials['BuildingMat-00049']} position={[9.183, -0.368, 2.965]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00050'].geometry} material={materials['BuildingMat-00050']} position={[9.183, -0.368, 2.965]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00051'].geometry} material={materials['BuildingMat-00051']} position={[9.183, -0.368, 2.215]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00052'].geometry} material={materials['BuildingMat-00052']} position={[9.183, 0.553, 3.714]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00053'].geometry} material={materials['BuildingMat-00053']} position={[9.183, 0.553, 2.965]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00055'].geometry} material={materials['BuildingMat-00055']} position={[9.183, -0.368, 3.714]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00057'].geometry} material={materials['BuildingMat-00057']} position={[9.183, -0.368, 4.464]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00058'].geometry} material={materials['BuildingMat-00058']} position={[9.183, -0.368, 5.214]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00061'].geometry} material={materials['BuildingMat-00061']} position={[9.183, -0.368, 5.963]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00062'].geometry} material={materials['BuildingMat-00062']} position={[9.183, -0.368, 6.713]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00063'].geometry} material={materials['BuildingMat-00063']} position={[8.227, 0.518, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00064'].geometry} material={materials['BuildingMat-00064']} position={[8.227, -1.325, 2.337]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00065'].geometry} material={materials['BuildingMat-00065']} position={[8.227, -1.325, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00066'].geometry} material={materials['BuildingMat-00066']} position={[8.227, 0.518, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00067'].geometry} material={materials['BuildingMat-00067']} position={[8.227, -1.325, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00068'].geometry} material={materials['BuildingMat-00068']} position={[8.227, -1.325, 6.834]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00070'].geometry} material={materials['BuildingMat-00070']} position={[8.227, -1.325, 8.333]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00075'].geometry} material={materials['BuildingMat-00075']} position={[8.227, 0.518, 6.834]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00077'].geometry} material={materials['BuildingMat-00077']} position={[6.29, -1.325, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00078'].geometry} material={materials['BuildingMat-00078']} position={[6.29, 0.518, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00079'].geometry} material={materials['BuildingMat-00079']} position={[6.29, 0.518, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00080'].geometry} material={materials['BuildingMat-00080']} position={[6.29, 0.518, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00081'].geometry} material={materials['BuildingMat-00081']} position={[6.29, -1.325, 2.337]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00082'].geometry} material={materials['BuildingMat-00082']} position={[6.29, 0.518, 2.337]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00083'].geometry} material={materials['BuildingMat-00083']} position={[6.29, -1.325, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00084'].geometry} material={materials['BuildingMat-00084']} position={[6.29, -1.325, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00085'].geometry} material={materials['BuildingMat-00085']} position={[8.227, 0.518, 8.333]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00086'].geometry} material={materials['BuildingMat-00086']} position={[6.29, 0.518, 6.834]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00087'].geometry} material={materials['BuildingMat-00087']} position={[6.29, -1.325, 6.834]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00088'].geometry} material={materials['BuildingMat-00088']} position={[6.29, 0.518, 8.333]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00091'].geometry} material={materials['BuildingMat-00091']} position={[6.29, -1.325, 8.333]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00092'].geometry} material={materials['BuildingMat-00092']} position={[6.29, -1.325, 8.333]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00097'].geometry} material={materials['BuildingMat-00097']} position={[6.29, 0.518, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00098'].geometry} material={materials['BuildingMat-00098']} position={[4.354, -1.325, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00100'].geometry} material={materials['BuildingMat-00100']} position={[4.354, 0.518, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00101'].geometry} material={materials['BuildingMat-00101']} position={[4.354, -1.325, -0.662]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00102'].geometry} material={materials['BuildingMat-00102']} position={[4.354, 0.518, 2.337]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00103'].geometry} material={materials['BuildingMat-00103']} position={[4.354, 0.518, 2.337]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00104'].geometry} material={materials['BuildingMat-00104']} position={[4.354, -1.325, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00105'].geometry} material={materials['BuildingMat-00105']} position={[4.354, 0.518, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00106'].geometry} material={materials['BuildingMat-00106']} position={[4.354, -1.325, 2.336]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00107'].geometry} material={materials['BuildingMat-00107']} position={[4.354, 0.518, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00108'].geometry} material={materials['BuildingMat-00108']} position={[4.354, -1.325, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00110'].geometry} material={materials['BuildingMat-00110']} position={[4.354, -1.325, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00111'].geometry} material={materials['BuildingMat-00111']} position={[4.353, 0.518, 6.834]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00112'].geometry} material={materials['BuildingMat-00112']} position={[4.354, -1.325, 6.834]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00114'].geometry} material={materials['BuildingMat-00114']} position={[4.353, 0.518, 8.333]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00116'].geometry} material={materials['BuildingMat-00116']} position={[4.353, -1.325, 8.333]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00117'].geometry} material={materials['BuildingMat-00117']} position={[2.417, -1.325, -3.66]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00120'].geometry} material={materials['BuildingMat-00120']} position={[2.417, -1.325, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00121'].geometry} material={materials['BuildingMat-00121']} position={[2.417, -1.325, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00122'].geometry} material={materials['BuildingMat-00122']} position={[2.417, 0.518, -0.662]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00123'].geometry} material={materials['BuildingMat-00123']} position={[2.417, 0.518, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00124'].geometry} material={materials['BuildingMat-00124']} position={[2.417, 0.518, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00126'].geometry} material={materials['BuildingMat-00126']} position={[2.417, -1.325, -0.662]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00127'].geometry} material={materials['BuildingMat-00127']} position={[2.417, 0.518, 2.337]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00129'].geometry} material={materials['BuildingMat-00129']} position={[2.417, -1.325, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00130'].geometry} material={materials['BuildingMat-00130']} position={[2.417, -1.325, 2.336]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00131'].geometry} material={materials['BuildingMat-00131']} position={[2.417, -1.325, 2.336]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00132'].geometry} material={materials['BuildingMat-00132']} position={[2.417, 0.518, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00133'].geometry} material={materials['BuildingMat-00133']} position={[2.417, -1.325, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00134'].geometry} material={materials['BuildingMat-00134']} position={[2.417, 0.518, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00135'].geometry} material={materials['BuildingMat-00135']} position={[2.417, -1.325, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00137'].geometry} material={materials['BuildingMat-00137']} position={[0.48, -1.325, -6.659]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00138'].geometry} material={materials['BuildingMat-00138']} position={[2.417, 0.518, 6.834]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00139'].geometry} material={materials['BuildingMat-00139']} position={[2.417, -1.325, 6.834]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00140'].geometry} material={materials['BuildingMat-00140']} position={[0.48, 0.518, -3.66]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00141'].geometry} material={materials['BuildingMat-00141']} position={[0.48, -1.325, -5.159]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00142'].geometry} material={materials['BuildingMat-00142']} position={[0.48, 0.518, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00143'].geometry} material={materials['BuildingMat-00143']} position={[0.48, 0.518, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00145'].geometry} material={materials['BuildingMat-00145']} position={[0.48, -1.325, -3.66]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00146'].geometry} material={materials['BuildingMat-00146']} position={[0.48, 0.518, -0.662]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00147'].geometry} material={materials['BuildingMat-00147']} position={[2.417, 0.518, -3.66]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00149'].geometry} material={materials['BuildingMat-00149']} position={[0.48, -1.325, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00151'].geometry} material={materials['BuildingMat-00151']} position={[0.48, -1.325, -0.662]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00152'].geometry} material={materials['BuildingMat-00152']} position={[0.48, 0.518, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00154'].geometry} material={materials['BuildingMat-00154']} position={[0.48, -1.325, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00156'].geometry} material={materials['BuildingMat-00156']} position={[0.48, 0.518, 2.336]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00157'].geometry} material={materials['BuildingMat-00157']} position={[0.48, -1.325, 2.336]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00160'].geometry} material={materials['BuildingMat-00160']} position={[0.48, 0.518, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00161'].geometry} material={materials['BuildingMat-00161']} position={[0.48, -1.325, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00162'].geometry} material={materials['BuildingMat-00162']} position={[0.48, 0.518, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00163'].geometry} material={materials['BuildingMat-00163']} position={[-1.457, -1.325, -8.158]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00164'].geometry} material={materials['BuildingMat-00164']} position={[0.48, -1.325, 5.335]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00165'].geometry} material={materials['BuildingMat-00165']} position={[0.48, 0.518, -5.159]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00166'].geometry} material={materials['BuildingMat-00166']} position={[-1.457, -1.325, -6.658]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00170'].geometry} material={materials['BuildingMat-00170']} position={[-1.457, -1.325, -5.159]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00171'].geometry} material={materials['BuildingMat-00171']} position={[-1.457, 0.518, -3.66]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00172'].geometry} material={materials['BuildingMat-00172']} position={[-1.457, 0.518, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00174'].geometry} material={materials['BuildingMat-00174']} position={[-1.457, -1.325, -3.66]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00176'].geometry} material={materials['BuildingMat-00176']} position={[-1.457, -1.325, -2.161]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00177'].geometry} material={materials['BuildingMat-00177']} position={[-1.457, 0.518, -6.659]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00179'].geometry} material={materials['BuildingMat-00179']} position={[-1.457, -1.325, -0.662]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00180'].geometry} material={materials['BuildingMat-00180']} position={[-1.457, 0.518, -5.159]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00181'].geometry} material={materials['BuildingMat-00181']} position={[-3.393, 0.518, -6.658]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00182'].geometry} material={materials['BuildingMat-00182']} position={[-1.457, 0.518, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00183'].geometry} material={materials['BuildingMat-00183']} position={[-1.457, -1.325, 0.837]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00184'].geometry} material={materials['BuildingMat-00184']} position={[-1.457, 0.518, -0.662]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00187'].geometry} material={materials['BuildingMat-00187']} position={[-1.457, -1.325, 2.336]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00190'].geometry} material={materials['BuildingMat-00190']} position={[-3.369, -3.239, -6.416]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00191'].geometry} material={materials['BuildingMat-00191']} position={[-1.457, -1.325, 3.836]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00193'].geometry} material={materials['BuildingMat-00193']} position={[-3.393, 0.518, -8.158]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00195'].geometry} material={materials['BuildingMat-00195']} position={[-3.37, 0.447, -3.418]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00198'].geometry} material={materials['BuildingMat-00198']} position={[-3.369, -3.239, -3.417]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00200'].geometry} material={materials['BuildingMat-00200']} position={[-3.369, 0.447, -0.419]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00202'].geometry} material={materials['BuildingMat-00202']} position={[-3.369, -3.239, -0.419]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00203'].geometry} material={materials['BuildingMat-00203']} position={[-1.457, 0.518, 2.336]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00206'].geometry} material={materials['BuildingMat-00206']} position={[-3.37, 0.447, 2.579]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00207'].geometry} material={materials['BuildingMat-00207']} position={[-3.369, -3.239, 2.579]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00208'].geometry} material={materials['BuildingMat-00208']} position={[-5.33, 0.518, -8.158]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00209'].geometry} material={materials['BuildingMat-00209']} position={[-5.33, 0.518, -6.658]} rotation={[0, 0, 1.571]} scale={0.008} />
      <mesh geometry={nodes['BuildingMesh-00219'].geometry} material={materials['BuildingMat-00219']} position={[-7.243, 0.447, -6.416]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00223'].geometry} material={materials['BuildingMat-00223']} position={[-7.243, 0.447, -3.417]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00224'].geometry} material={materials['BuildingMat-00224']} position={[-7.243, -3.239, -6.416]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00228'].geometry} material={materials['BuildingMat-00228']} position={[-7.243, -3.239, -3.417]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00229'].geometry} material={materials['BuildingMat-00229']} position={[-7.243, -3.239, -0.419]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00230'].geometry} material={materials['BuildingMat-00230']} position={[-7.243, 0.447, -0.419]} rotation={[0, 0, 1.571]} scale={0.016} />
      <mesh geometry={nodes['BuildingMesh-00282'].geometry} material={materials['BuildingMat-00282']} position={[10.152, 0.553, 4.464]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00284'].geometry} material={materials['BuildingMat-00284']} position={[9.183, 0.553, 4.464]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00285'].geometry} material={materials['BuildingMat-00285']} position={[9.183, 0.553, 5.214]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
      <mesh geometry={nodes['BuildingMesh-00286'].geometry} material={materials['BuildingMat-00286']} position={[9.183, -0.368, 7.462]} rotation={[0, 0, Math.PI / 2]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('models/parcCientific.glb')
